detect_weight_path: "weights/best.pt"
pose_weight_path: "weights/yolov7-w6-pose.pt"
source_path: "inference/videos/demo.mp4"
save_path: "inference/videos/demo_dst.mp4"
img_size: 640
conf_thres: 0.5
iou_thres: 0.35
device: "0"
display: true
agnostic_nms: false
trace: true
